### ISSUE TITLE
It's unnecessary to provide get_group_ids and add_user_to_group API

### ISSUE THREAD

**Issue by 0x1b2c** [transist/echidna-streaming#28]
Streaming should be able to add user to group immediately just after add user, it's unnecessary to make spider call these 2 API.

**Comment by rngadam** [comment]
Looking at: 

https://github.com/transist/echidna-streaming/blob/master/bin/worker.rb

already fetching group internally here:

```
      group_id = User.new("id" => message["body"]["user_id"], "type" => message["body"]["user_type"])['group_id']
```

so yes, it's unnecessary to provide the API function to the spider since it's taken care of internally in echidna-streaming.

**Comment by rngadam** [comment]
call add_user_to_group logic inside add_user logic.

**Comment by rngadam** [comment]
also remove from https://github.com/transist/echidna-streaming/edit/master/trends.rb, remove:

```
    when "/get_group_ids" # for echidna-spider
      response_body = $cacher.fetch "cache/#{params.slice('gender', 'birth_year', 'city').values.join('/')}/group_ids", :expires_in => 86400 do
        group_ids = Group.find_group_ids(params["gender"], params["birth_year"], params["city"])
        MultiJson.encode("ids" => group_ids)
      end
      [200, {}, response_body]
    end
```
